# Generated by Django 3.1.7 on 2021-04-05 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_auto_20210404_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenStucture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topLeftx', models.PositiveIntegerField()),
                ('topLefty', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('BUILD', 'Building'), ('WATER', 'Water Feature'), ('CONT', 'Container'), ('PATH', 'Path')], default='Build', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='garden',
            name='length',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30, 'length cannot exceed 30 meters')]),
        ),
        migrations.AlterField(
            model_name='garden',
            name='width',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30, 'width cannot exceed 30 meters')]),
        ),
    ]
