# Generated by Django 3.1.7 on 2021-04-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_auto_20210405_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='structures',
        ),
        migrations.AddField(
            model_name='gardenstructure',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garden.garden'),
        ),
    ]
